"""Gera o conjunto de teste escrito à mão (dados/teste.jsonl).

Os pedidos aqui não vêm dos modelos de frase de gerar_dados.py: têm outra redação, outros
assuntos e alguns casos de fronteira, para medir se o roteador generaliza em vez de decorar.
"""
import json
import os

from perguntas import QUESTIONS

HAIKU = [
    "quem escreveu Dom Casmurro?",
    "Who painted the Mona Lisa?",
    "me diz rapidinho quantos centímetros tem um metro",
    "how do you say 'cheers' in German",
    "Qual o plural de 'cidadão'?",
    "is a tomato a fruit or a vegetable?",
    "Coloca em maiúsculas: relatório final de vendas",
    "What's 15% of 80?",
    "obrigado, era só isso mesmo",
    "thanks, that's all I needed!",
    "Qual a diferença entre 'mas' e 'mais'?",
    "What time zone is Lisbon in?",
    "Me dá uma palavra que rime com 'coração'",
    "Spell 'necessary' for me",
    "Quantos estados tem o Brasil?",
    "Who is the author of 1984?",
    "Escreve 'feliz aniversário' em italiano",
    "What's the boiling point of water in Fahrenheit?",
    "qual é a raiz quadrada de 144",
    "Round 3.14159 to two decimal places",
    "Transforma essa data em formato americano: 25/12/2026",
    "What's the opposite of 'generous'?",
    "Quanto é 1 dólar em centavos?",
    "Is Sydney the capital of Australia?",
    "Abrevie a palavra 'avenida'",
    "List the days of the week in French",
    "Qual é o maior planeta do sistema solar?",
    "How many players are on a soccer team?",
    "Coloca vírgula certinha: 'João meu amigo chegou'",
    "Capitalize this title: the old man and the sea",
    "Que dia da semana foi 1º de janeiro de 2026?",
    "What is the chemical symbol for gold?",
    "bom dia! tudo certo por aí?",
    "hey, quick one: what's the plural of 'mouse'?",
    "Quantos gramas tem um quilo?",
    "Which ocean is the largest?",
    "Traduz 'saudade' pro inglês",
    "What does 'ASAP' mean?",
    "Separe as sílabas de 'paralelepípedo'",
    "Who was the first president of the United States?",
    "Qual a moeda do Japão?",
    "Convert 2 hours into minutes",
    "Reescreva em negrito markdown a palavra atenção",
    "How many continents are there?",
    "Me lembra qual é o código de área de São Paulo",
    "Is 'irregardless' a real word?",
    "Qual é o feminino de 'ator'?",
    "Turn this into a bullet list: eggs, milk, bread",
    "Quem descobriu o Brasil?",
    "What's the square of 12?",
]

SONNET = [
    "meu script python tá dando 'ModuleNotFoundError: No module named requests', como resolvo?",
    "My Express server returns 404 for every route after I added a router, here's app.js",
    "Cria um endpoint FastAPI que recebe um JSON e salva no Postgres",
    "Add input validation to this Flask form handler",
    "Por que meu useEffect está rodando em loop infinito?",
    "Write a bash script that backs up a folder to S3 every night",
    "Transforma esse callback hell em async/await",
    "Convert this class component to a React hook-based component",
    "Escreve um regex que capture CEPs no formato 00000-000",
    "Write a Python script to rename all files in a folder by date",
    "Ajusta esse CSS pra o menu ficar responsivo no celular",
    "Why does git say 'detached HEAD' and how do I get back to my branch?",
    "Cria uma migration do Django que adiciona um campo de status no pedido",
    "Optimize this slow SQL query that uses three nested subqueries",
    "Me ajuda a escrever o README desse projeto com instruções de instalação",
    "Write a Go HTTP handler that streams a large file",
    "Implementa um cache em memória com expiração para essa função",
    "Add pagination to this GraphQL resolver",
    "Escreve um script que lê um Excel e gera um relatório em PDF",
    "My Docker container exits immediately with code 137, what's wrong?",
    "Converte esse código Java para Kotlin",
    "Write Jest tests for this shopping cart reducer",
    "Resolve o conflito de merge nesse arquivo de configuração",
    "Parse this XML response and extract the order IDs in TypeScript",
    "Monta um docker-compose com app Node, Postgres e Redis",
    "Add structured logging to this Python service",
    "Escreve uma carta de apresentação para uma vaga de analista de dados",
    "Rewrite this product description to be more persuasive, about 200 words",
    "Resume essa thread longa de e-mails e lista as pendências",
    "Write a cron expression and a script that cleans old logs weekly",
    "Corrige o erro de CORS que aparece quando o front chama a API",
    "Implement binary search in Rust with tests",
    "Cria um script em Python que consome a API do GitHub e lista os PRs abertos",
    "My pandas merge is producing duplicate rows, help",
    "Faz uma planilha de orçamento mensal com fórmulas",
    "Write a Terraform module for an S3 bucket with versioning",
    "Explica esse erro de TypeScript: 'Type string is not assignable to type number'",
    "Debug why my unit test passes locally but fails in CI",
    "Escreve um post de LinkedIn anunciando o lançamento do nosso produto",
    "Implement JWT authentication middleware for my Express app",
    "Gera dados falsos para popular o banco de testes",
    "Fix the off-by-one error in this loop",
    "Cria uma função que calcula juros compostos com aportes mensais",
    "Write a Kubernetes deployment YAML for this service",
    "Adiciona tratamento de erros nessa chamada HTTP",
    "Summarize this 20-page PDF about our new HR policy",
    "Faz um script que monitora um site e avisa no Telegram se cair",
    "Convert this JSON schema into Pydantic models",
    "Me explica como funciona esse hook customizado e onde ele pode quebrar",
    "Write a GitHub Action that publishes the package to npm on tag",
]

OPUS = [
    "Preciso migrar um monólito de 15 anos para microsserviços sem parar a operação; desenhe a estratégia completa",
    "Design a globally distributed rate limiter that stays accurate under network partitions",
    "Demonstre formalmente que o problema da parada é indecidível",
    "Prove that every bounded monotone sequence of real numbers converges",
    "Analise os trade-offs entre consistência eventual e forte para nosso sistema de estoque com 40 centros de distribuição",
    "Our recommendation system's engagement dropped 20% after a model update; walk through a full root-cause investigation plan",
    "Elabore um plano de pesquisa para testar se modelos de linguagem desenvolvem representações de mundo internas",
    "Design a zero-downtime schema migration strategy for a 5 TB Postgres database with heavy write traffic",
    "Avalie se devemos construir ou comprar nossa plataforma de dados, considerando custo total em 5 anos, riscos e equipe",
    "Derive the backpropagation equations for a transformer attention layer from scratch",
    "Projete um protocolo de consenso tolerante a falhas bizantinas para uma rede de 50 bancos",
    "Write a rigorous threat model for a mobile banking app, including attacker profiles and mitigations",
    "Resolva e demonstre: quantas formas existem de ladrilhar um tabuleiro 2xn com dominós? Generalize",
    "Compare three approaches to exactly-once processing in stream pipelines and recommend one for our fraud detection use case",
    "Analise a viabilidade econômica e regulatória de lançar um banco digital no Brasil",
    "Design an experiment framework that corrects for network effects in a two-sided marketplace A/B test",
    "Explique e prove a complexidade amortizada da estrutura union-find com compressão de caminho",
    "We have intermittent data corruption across replicas only under specific failover sequences; hypothesize causes and design tests to isolate them",
    "Crie uma arquitetura de IA multiagente para automatizar o atendimento jurídico, com governança e avaliação",
    "Assess the long-term implications of quantum computing on our current encryption, and plan a migration roadmap",
    "Desenvolva um modelo matemático para otimizar a alocação de leitos de UTI em uma rede de hospitais",
    "Critically evaluate the evidence for and against the efficient market hypothesis",
    "Projete do zero um compilador para uma linguagem com tipos dependentes, explicando as decisões de design",
    "Find and prove a tight lower bound for comparison-based sorting",
    "Faça uma análise profunda de por que nosso modelo de previsão de demanda erra sistematicamente em feriados e proponha uma nova abordagem",
    "Design the data architecture for a national health records system with privacy guarantees",
    "Compare as teorias de justiça de Rawls e Nozick e aplique ao debate sobre renda básica universal",
    "Plan a multi-year roadmap to make our ML platform reproducible, auditable and cost-efficient across 12 teams",
    "Projete um sistema de detecção de anomalias em tempo real para 10 milhões de sensores IoT com orçamento limitado",
    "Analyze whether our microservices should share a database, considering coupling, consistency and team topology, and give a recommendation",
    "Elabore uma prova de que o algoritmo de Kruskal sempre encontra a árvore geradora mínima",
    "Design a sharding strategy for a social graph with celebrity hotspots",
    "Investigue as causas possíveis de vazamento de memória lento em uma JVM que roda há semanas e monte um plano de diagnóstico",
    "Propose a novel approach to reduce hallucinations in retrieval-augmented generation and design an evaluation",
    "Modele o risco de crédito de uma carteira de PMEs considerando correlação entre setores",
    "Write a detailed technical design doc for an offline-first sync engine with conflict resolution",
    "Estruture um plano de transformação digital para uma rede de 300 farmácias, com fases, riscos e indicadores",
    "Formally verify that this lock-free queue is linearizable",
    "Compare as abordagens de RLHF, DPO e constitutional AI, discutindo limitações teóricas de cada uma",
    "Design a pricing algorithm for ride sharing that balances supply, demand and fairness",
    "Projete a estratégia de recuperação de desastres para um data center que hospeda sistemas críticos de saúde",
    "Explain and prove why the simplex method can take exponential time in the worst case",
    "Analise as consequências de segunda ordem de uma regulamentação que proíba IA em decisões de crédito",
    "Design a multi-region active-active architecture for a trading platform with sub-10ms latency",
    "Avalie criticamente três arquiteturas possíveis para nosso novo produto e recomende uma, justificando com custos e riscos",
    "Develop a causal inference strategy to measure the impact of a policy change with no control group",
    "Elabore uma demonstração do teorema fundamental da aritmética",
    "Investigate why our distributed training job diverges only at scale above 256 GPUs",
    "Projete um mecanismo de leilão à prova de manipulação para alocar espectro de rádio",
    "Design an end-to-end system to detect coordinated inauthentic behavior on a social network",
]


def main():
    rows = [(t, "haiku") for t in HAIKU] + [(t, "sonnet") for t in SONNET] + [(t, "opus") for t in OPUS]
    os.makedirs("dados", exist_ok=True)
    with open("dados/teste.jsonl", "w", encoding="utf-8") as f:
        for text, label in rows:
            f.write(json.dumps({"state": text, "questions": QUESTIONS, "expected": {"modelo": label}},
                               ensure_ascii=False) + "\n")
    print(len(rows), "exemplos de teste")


if __name__ == "__main__":
    main()
